spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # create tables from your JPA entities for tests
    defer-datasource-initialization: true # <-- run data.sql AFTER JPA creates tables
  sql:
    init:
      mode: always # allow running schema/data scripts on embedded DBs

